### ISSUE TITLE
Window doesn't populate when opening the titles

### ISSUE THREAD

**Issue by erdelf** [mabako/TitleRoulette#1]
The title roulette window continously stays on "Please open 'Character' > 'Acquired Titles' once" and doesn't populate when the title window is opened.
Can't see any issues in the log.

**Comment by cadooron2** [comment]
Same here, seems to just not work

**Comment by mabako** [comment]
Will be fixed when 9eaa4e6fab96736639c1e307506ec8622125c545 is merged in the upstream plugin repo.
